# Generated by Django 4.2.23 on 2025-10-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
