# Generated by Django 4.2.23 on 2025-10-19 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_workspace_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspace",
            old_name="create_by",
            new_name="created_by",
        ),
    ]
