# Generated by Django 4.2.23 on 2025-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_rename_create_by_workspace_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
