# Generated by Django 4.2.23 on 2025-10-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0004_alter_workspace_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
