# Generated by Django 4.2.23 on 2025-10-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_action_workspaces", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
