# Generated by Django 4.2.23 on 2025-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systeminfo",
            name="allow_custom_background_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systeminfo",
            name="default_background_image",
            field=models.FileField(blank=True, null=True, upload_to="backgrounds/"),
        ),
    ]
