# Generated by Django 4.2.23 on 2025-11-10 15:36

from django.db import migrations, models
import django_resized.forms
import system.models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_systeminfo_allow_custom_background_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systeminfo",
            old_name="allow_custom_background_image",
            new_name="allow_background_image",
        ),
        migrations.AddField(
            model_name="systeminfo",
            name="allow_user_custom_background_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="systeminfo",
            name="default_background_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=(1920, 1080),
                upload_to=system.models.generate_default_background_path,
            ),
        ),
    ]
