# Generated by Django 4.2.23 on 2025-11-10 16:58

from django.db import migrations
import django_resized.forms
import jumper.storage_utils.file_field


class Migration(migrations.Migration):
    dependencies = [
        (
            "system",
            "0003_rename_allow_custom_background_image_systeminfo_allow_background_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="systeminfo",
            name="default_background_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=(1920, 1080),
                upload_to=jumper.storage_utils.file_field.FileFieldPathFactory.build_instance_path,
            ),
        ),
    ]
