# Generated by Django 4.2.23 on 2025-11-11 11:53

from django.db import migrations, models
import django_resized.forms
import system.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system",
            "0003_rename_allow_custom_background_image_systeminfo_allow_background_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="systeminfo",
            name="allow_action_sections",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systeminfo",
            name="allow_users_to_hide_actions",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="systeminfo",
            name="default_background_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=(1920, 1080),
                upload_to=system.models.background_upload_to,
            ),
        ),
    ]
