# Generated by Django 4.2.23 on 2025-11-11 10:13

from django.db import migrations, models
import django_resized.forms
import jumper.storage_utils.file_field


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_alter_systeminfo_default_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="systeminfo",
            name="allow_action_sections",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systeminfo",
            name="allow_users_to_hide_actions",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="systeminfo",
            name="default_background_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=(1920, 1080),
                upload_to=jumper.storage_utils.file_field.FileFieldPathFactory.build_instance_path,
            ),
        ),
    ]
