# Generated by Django 4.2.19 on 2025-03-01 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="create_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="actions", to="users.group"
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="actions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="actions_act_content_f49b3a_idx",
            ),
        ),
    ]
