# Generated by Django 4.2.19 on 2025-03-02 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0003_historicalpythonactiondata_historicallinkactiondata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="type",
        ),
    ]
