# Generated by Django 4.2.19 on 2025-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("actions", "0004_remove_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="actions", to="users.role"
            ),
        ),
    ]
