# Generated by Django 4.2.20 on 2025-04-12 09:30

import actions.models.action_models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0005_action_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="is_active",
            field=models.BooleanField(default=False, help_text="Is the action active?"),
        ),
        migrations.AlterField(
            model_name="action",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="PNG",
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=(80, 80),
                upload_to=actions.models.action_models.generate_thumbnail_path,
            ),
        ),
        migrations.AlterField(
            model_name="historicallinkactiondata",
            name="url",
            field=models.URLField(default="https://example.com"),
        ),
        migrations.AlterField(
            model_name="historicalpythonactiondata",
            name="code",
            field=models.TextField(default="print('Hello World!')"),
        ),
        migrations.AlterField(
            model_name="linkactiondata",
            name="url",
            field=models.URLField(default="https://example.com"),
        ),
        migrations.AlterField(
            model_name="pythonactiondata",
            name="code",
            field=models.TextField(default="print('Hello World!')"),
        ),
    ]
