# Generated by Django 4.2.20 on 2025-04-20 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("actions", "0007_action_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindowsCMDActionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(default="echo Hello world")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="historicalpythonactiondata",
            name="code",
            field=models.TextField(default="def run():\r\n    print('Hello world')"),
        ),
        migrations.AlterField(
            model_name="pythonactiondata",
            name="code",
            field=models.TextField(default="def run():\r\n    print('Hello world')"),
        ),
        migrations.CreateModel(
            name="HistoricalWindowsCMDActionData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.TextField(default="echo Hello world")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical windows cmd action data",
                "verbose_name_plural": "historical windows cmd action datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
