# Generated by Django 4.2.20 on 2025-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0008_windowscmdactiondata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpythonactiondata",
            name="combobox_code",
            field=models.TextField(
                default="def get_options():\r\n    return ['Option 1', 'Option 2']"
            ),
        ),
        migrations.AddField(
            model_name="historicalpythonactiondata",
            name="use_combobox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pythonactiondata",
            name="combobox_code",
            field=models.TextField(
                default="def get_options():\r\n    return ['Option 1', 'Option 2']"
            ),
        ),
        migrations.AddField(
            model_name="pythonactiondata",
            name="use_combobox",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicalwindowscmdactiondata",
            name="code",
            field=models.TextField(default="@echo off\r\n\r\necho Hello world"),
        ),
        migrations.AlterField(
            model_name="windowscmdactiondata",
            name="code",
            field=models.TextField(default="@echo off\r\n\r\necho Hello world"),
        ),
    ]
