# Generated by Django 4.2.20 on 2025-04-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0009_historicalpythonactiondata_combobox_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwindowscmdactiondata",
            name="combobox_code",
            field=models.TextField(
                default="def get_options(context):\r\n    return ['Option 1', 'Option 2']"
            ),
        ),
        migrations.AddField(
            model_name="historicalwindowscmdactiondata",
            name="use_combobox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="windowscmdactiondata",
            name="combobox_code",
            field=models.TextField(
                default="def get_options(context):\r\n    return ['Option 1', 'Option 2']"
            ),
        ),
        migrations.AddField(
            model_name="windowscmdactiondata",
            name="use_combobox",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicalpythonactiondata",
            name="combobox_code",
            field=models.TextField(
                default="def get_options(context):\r\n    return ['Option 1', 'Option 2']"
            ),
        ),
        migrations.AlterField(
            model_name="pythonactiondata",
            name="combobox_code",
            field=models.TextField(
                default="def get_options(context):\r\n    return ['Option 1', 'Option 2']"
            ),
        ),
    ]
