# Generated by Django 4.2.23 on 2025-09-13 15:18

import actions.models.action_data_models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0010_historicalwindowscmdactiondata_combobox_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallinkactiondata",
            name="url",
            field=models.CharField(
                default="https://example.com",
                max_length=1048,
                validators=[actions.models.action_data_models.validate_url_format],
            ),
        ),
        migrations.AlterField(
            model_name="linkactiondata",
            name="url",
            field=models.CharField(
                default="https://example.com",
                max_length=1048,
                validators=[actions.models.action_data_models.validate_url_format],
            ),
        ),
    ]
