# Generated by Django 4.2.23 on 2025-09-28 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0013_alter_historicalaction_thumbnail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalaction_roles",
            name="action",
        ),
        migrations.RemoveField(
            model_name="historicalaction_roles",
            name="history",
        ),
        migrations.RemoveField(
            model_name="historicalaction_roles",
            name="role",
        ),
        migrations.RemoveField(
            model_name="historicalaction_users",
            name="action",
        ),
        migrations.RemoveField(
            model_name="historicalaction_users",
            name="history",
        ),
        migrations.RemoveField(
            model_name="historicalaction_users",
            name="user",
        ),
        migrations.DeleteModel(
            name="HistoricalAction_groups",
        ),
        migrations.DeleteModel(
            name="HistoricalAction_roles",
        ),
        migrations.DeleteModel(
            name="HistoricalAction_users",
        ),
    ]
