# Generated by Django 4.2.23 on 2025-10-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
        ("actions", "0015_historicalaction_users_historicalaction_roles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="historicalaction",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
    ]
