# Generated by Django 4.2.23 on 2025-11-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0016_action_workspace_historicalaction_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="section",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalaction",
            name="section",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
