# Generated by Django 4.2.23 on 2025-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_assign_admin_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="system_role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("action_manager", "Action Manager"),
                    ("user_manager", "User Manager"),
                    ("user", "User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
