# Generated by Django 4.2.23 on 2025-11-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import jumper.storage_utils.file_field


def create_user_preferences_for_existing_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserPreferences = apps.get_model("users", "UserPreferences")
    for user in User.objects.all():
        UserPreferences.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_system_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disable_default_background_image",
                    models.BooleanField(default=False),
                ),
                (
                    "custom_background_image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format="PNG",
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=(1920, 1080),
                        upload_to=jumper.storage_utils.file_field.FileFieldPathFactory.build_instance_path,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_user_preferences_for_existing_users,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
